### ISSUE TITLE
Crash if files passed in build.commands are not executable

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#1]
Example:

```yml
build:
    commands:
        - deploy/hooks/00_assert_no_debug.sh
```

--> Crash if deploy/hooks/00_assert_no_debug.sh is not executable
--> We should just check that
