### ISSUE TITLE
tests on jenkins fail because of persistent postgres volume

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#124]
Since yesterday we got tests on jenkins failing because of wrong postgres state. Previously it was a clean state each run. Since #123 it is not.

Incriminating usage:
```
docker_links:
  - image_name: postgres:9.6
    link_name: db
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
```

Previously `docker_links.volumes` were only used for shell, #123 changed that, to be able to have volumes sharing between docker_links and services even at test time. But it's not strictly needed: use `testing_options` instead.
