### ISSUE TITLE
`env` not usable in `data_volumes` when `run`ning a service

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#145]
```
env:
  default:
    source: ${DEEPOMATIC_CONFIG_DIR}/dev.sh
    variables:
      DATASETS_PATH: ${DATASETS_PATH:-/tmp/datasets}
...
services:
  - service_name: myservice
...
    tests:
      data_volumes:
        - container_volume: /input_datasets
          source: ${DATASETS_PATH}
```
This fails with `Field source must be a host path or start with 's3://'` when the service is run (for example with `dmake run`, or as a dependency of another service, with `dmake test`).

We expect to have evaluation from `env`.

Effectively it works like that when the service is executed with shell or test.

This is a limitation of #131 which added `data_volumes` to `run`.
