### ISSUE TITLE
Customize environment variables per service in addition to per dmake.yml file

### ISSUE THREAD

**Issue by Alexis-Jacob** [Deepomatic/dmake#159]
I would like to specify env variables for a service instead of globally

**Comment by maingoh** [comment]
Like this ? 
```
    -
        service_name: my_service
        deploy:
            stages:
                -
                    description: Deploying Cluster 1 (prod)
                    branches: master
                    env:
                        MY_VAR: 1
```
