### ISSUE TITLE
Add env_exports for needed_services

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#271]
For `needed_links` we can inject env vars to the services using them by adding `env_exports` on the `docker_links` definition (alongside `env` that overrides the runtime env for the docker link itself).

We would like to have that for `needed_services` too. Ideally we should have both `env_exports` and `env` at the service definition level, but we currently have neither (`env` at service level is a feature tracked here #159).
What we can easily do however is to add `env_exports` at the `needed_services` level: when defining how we want the dependency service.

Example:
```
  - service_name: e2e
    needed_services:
     - service_name: web
       link_name: web
       env_exports:
         WEB_URL: http://web:8000
```

This way we can still later add back `env` and `env_from` at the service definition level if needed.
