### ISSUE TITLE
commands in tests.commands is bash-evaluated too early

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#272]
```
...
env:
  default:
    URL: http://foo

services:
  - service_name: e2e
...
    tests:
      commands:
        - curl -sSf "${URL}/api"
```
Results in this command being run in `docker run`: 
```
bash -c "curl -sSf \"/api\""
```
=> the `${URL}` part seems to be evaluated before reaching the container...
