### ISSUE TITLE
kubernetes deployment: support creating secrets like config maps from files

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#291]
Following up on #41, we should add support to create kubernetes secrets from files.

Something like:
```yaml
          kubernetes:
            secrets:
              - name: my-secret
                generic:
                  from_files:
                    - key: ssh-privatekey
                      path: $HOME/.ssh/id_rsa
                    - key: ssh-publickey
                      path: $HOME/.ssh/id_rsa.pub
```
It should do the same thing as:
```shell
# Create a new secret named my-secret with specified keys instead of names on disk
kubectl create secret generic my-secret --from-file=ssh-privatekey=~/.ssh/id_rsa --from-file=ssh-publickey=~/.ssh/id_rsa.pub
```
