### ISSUE TITLE
Docker links volumes with path are not mounted in dmake run or dmake test command

### ISSUE THREAD

**Issue by maingoh** [Deepomatic/dmake#317]
```
volumes:
  - shared-volume

docker-links:
  - image_name: myimage
    volumes:
      - shared-volume:/var/lib/myimage
      - /mnt/myimage/apps/:/apps/
```

The first volume is always mounted (using a global shared volume), but when using hardcoded path it is only mounted in `dmake shell -d`, not `dmake run -d` or `dmake test -d`. You can do a docker inspect to make sure.
