### ISSUE TITLE
Do not include sources in the production image

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#37]
Proposal:
Specify a list of artefacts (files or directories) in the dmake file thay would need to be copied/added to the production image once the build has been done.

E.g. have an `artefacts` field under `build`:

```yaml
build:
  ...
  artefacts:
    - target_path: build/release/lib/libdeepomatic.so
       mount_dir: /usr/lib
```
