### ISSUE TITLE
dmake kubernetes deployment broken with container env value 'no'  

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#401]
kubernetes manifest template:
```
apiVersion: apps/v1
kind: Deployment
...
spec:
...
    spec:
      containers:
      - name: foo
        env:
        - name: FOO
          value: 'no'
```
dmake injects extra annotations and renders:
 ```
apiVersion: apps/v1
kind: Deployment
...
spec:
...
    spec:
      containers:
      - name: foo
        env:
        - name: FOO
          value: no
```

diff:
`'no'` became `no`, which in YAML 1.1 is a boolean, not a string. (In YAML 1.2 it is a string.)

This then breaks when applying on kubernetes: the env value must be a string.
