### ISSUE TITLE
Environment variables values should always be strings in dmake.yml

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#432]
```yaml
dmake_version: 0.1
app_name: env-test

env:
  default:
    variables:
      FOO: on

docker:
  root_image:
    name: ubuntu
    tag: 18.04

services:
  - service_name: foo
    config:
      docker_image: ubuntu:18.04
    tests:
      commands:
        - echo $FOO
```

Actual:
```
$ dmake test
...
 ## Running App ##
- Running test @ env-test/foo
+ echo True
True
```

Expected:
```
on
```

This is due to
- yaml having many boolean literals: https://yaml.org/type/bool.html
- dmake accidentally accepting booleans as environment variables values, because:
  -  dmake tries to convert non strings to strings there: https://github.com/Deepomatic/dmake/blob/3248370f76a59373b0c9dcf6c498c090ab134c2c/dmake/serializer.py#L130-L141
  - dmake doesn't explicitly supports booleans, but in python `isinstance(True, int)` returns True.

What I propose is a slow migration toward what kubernetes does: when it wants strings it mandates string type in yaml: early failure is better than unexpected env var values at runtime...
