### ISSUE TITLE
Can't deploy Ingress

### ISSUE THREAD

**Issue by JulienFS** [Deepomatic/dmake#494]
When I try to deploy a service with manifests described as this :
``` 
manifests:
  - template: deploy/reverse_proxy/deployment.yml
    variables:
      K8S_IMAGE_PULL_POLICY: ${K8S_IMAGE_PULL_POLICY}
  - template: deploy/reverse_proxy/service.yml
  - template: deploy/reverse_proxy/ingress.yml
    variables:
      HOSTNAMES: ${HOSTNAMES}
      CERTIFICATES: ${CERTIFICATES}
  - template: deploy/reverse_proxy/managed_certificate_development.yml
 ```

With an Ingress in the `ingress.yml` starting with : 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
```
I get the following error :

`error: error retrieving RESTMappings to prune: invalid resource networking.k8s.io/v1, Kind=Ingress, Namespaced=true: no matches for kind "Ingress" in version "networking.k8s.io/v1"`
