### ISSUE TITLE
cannot convert int64 to string : Env variable type lost when used as manifest variable

### ISSUE THREAD

**Issue by JulienFS** [Deepomatic/dmake#495]
If I have something like this in my DMakefile :
```
env:
  default:
    variables:
      MY_VARIABLE: '1234'

services:
    deploy:
      stages:
          kubernetes:
            manifests:
              - template: my_template.yml
                variables:
                  MY_VARIABLE: ${MY_VARIABLE}
```

and this in `my_template.yml` :

```
spec:
  template:
    spec:
      containers:
        env:
          - name: MY_VARIABLE
            value: ${MY_VARIABLE}
```

`dmake deploy` will fail with the following message :
`cannot convert int64 to string`

However if if quote `my_template.yml` like this :
```
spec:
  template:
    spec:
      containers:
        env:
          - name: MY_VARIABLE
            value: '${MY_VARIABLE}' # <========
```

It works. So it seems that the original string variable is implicitly converted to int.
