### ISSUE TITLE
use env variable as kubernetes template file path

### ISSUE THREAD

**Issue by JulienFS** [Deepomatic/dmake#496]
I need to deploy different kubernetes certificates depending on build target (staging/dev).
I wish I could use an env variable in the DMakefile to specifcy the path like so :
```
env:
  default:
    variables:
      MY_CERT_PATH: option_1.yml
  branches:
    staging:
      variables:
        MY_CERT_PATH: option_2.yml
...
kubernetes:
  - template: ${MY_CERT_PATH}
```

But it seems that variables are not allowed here.
I tried to work around by using the branch selector for stages but since '*' stands for every branch and not for a "case else" for matched branches I would end up deploying both certificates when deploying on staging.
